import type { DocStep } from '../docsContent'

export const syntheticDataSteps: DocStep[] = [
  {
    title: 'Dataset Generation Setup',
    description:
      'Build the base Blender scene, load target assets, and initialize camera trajectories and sensor parameters.',
    file: 'data generator/main.py',
    to: '/synthetic-data/scene-camera-initialization',
    notes: [
      'Load the Blender Scene, get Object and Camera references.',
      'Setup Data Generation parameters under data generator/config.py.',
      'Setup Randomization parameters to enable domain variability.',
    ],
    sections: [
      {
        heading: 'Multi-Class Keypoint Dataset Setup',
        body: `Multi-class in the context of our synthetic data generation refers to the ability to create dataset that includes multiple distinct object classes, each with their own set of keypoints.
In our case, we have four classes faceA, faceB, faceC, and faceD (However, physically they are located in the same single spacecraft). Instead of treating the spacecraft as a single object class,
we define each face as a separate class with its own keypoints. This allows us to work with only visible keypoints for each face while solving the pose using PnP algorithm, which improves the 
accuracy and robustness of pose estimation.
        
`
      },
      {
        heading: 'Data Organization in Blender',
        body: `
The Blender file with the complete scene setup can be loaded into Blender to inspect the organization of objects and collections. The file format is .blend.
Assign a unique name to each object class. Separate them into different collections in Blender for better organization and easier access during data generation.
Assign an empty object as the parent for the entire spacecraft model. This allows us to manipulate the entire spacecraft as a single unit while still maintaining 
the ability to access and manipulate individual faces as separate objects. Also, separate the keypoints for each face into different collections. The keypoints
can be represented as small spheres or empties in Blender, and they should be named according to their corresponding face and keypoint index (e.g., faceA_kp1, faceA_kp2, ..., faceD_kpN)
for easy identification and access. The keypoints should also be parented to their respective face objects or the main spacecraft parent object.
This way, we can easily access the keypoints for each face during annotation and label extraction. Define the camera sensor parameters as necessary.
\n
Use the Blender Python API to access and manipulate these objects during the data generation process. For example, you can use bpy.data.objects['object_name'] 
to get a reference to a specific object in the scene.

        `
      },

      {
        heading: 'Randomization for Domain Variability',
        body: `
To improve the generalization of models trained on synthetic data, we apply randomization to various aspects of the 
scene during data generation. This includes randomizing the position and orientation of the target object, randomizing
the camera position around the target object while maintaining a specified distance range, and randomizing the lighting
conditions in the scene. The randomization parameters and bounds can be configured in the config file (data generator/config.py).
It can also be applied selectively to specific parameters. Check the API documentation for the Randomizer class and RandomizerSettings class
for more details on the available randomization options and how to configure them.
Our current implementation randomizes the object position in X and Y axes, and randomizes the camera position in all X, Y, and Z axes 
while staying within the specified boundaries. The lighting conditions are randomized by changing the strength of the lights.
        `
      }

    ]
  },
  {
    title: 'Annotation and Label Extraction',
    description:
      'Generate 2D annotations from object transforms and camera projections for detector and keypoint supervision.',
    file: 'data generator/utils/bbox.py, data generator/utils/keypoints.py',
    to: '/synthetic-data/annotation-label-extraction',
    notes: [
      'bbox.py provides projection-aware bounding boxes.',
      'keypoints.py extract 2D keypoint locations from 3D transforms with visibility and occlusion information.',
    ],
    sections: [
      {
        heading: 'Extracting Bounding Boxes',
        body: `The bbox.py module contains functions to compute 2D bounding boxes for each class. 
The bounding boxes are generated by first converting the 3D vertices of the object into camera space and
checking which vertices are visible (i.e., in front of the camera) by evaluating the z-coordinate.
The visible vertices (3D world-space points) are then projected onto the 2D image plane using the camera's intrinsic parameters.
\n
Blender provided function world_to_camera_view() is used to project the 3D world-space points to 2D normalized device coordinates(NDC).
These normalized coordinates are then converted to pixel coordinates by multiplying with the image width and height.
\n
Finally, the 2D bounding box is computed by finding the minimum and maximum x and y coordinates among the projected points, which define the corners of the bounding box.
The resulting bounding box is represented as a tuple of (x_min, y_min, x_max, y_max) in pixel coordinates. 
(Note: This format may or may not be compatible with the export format. Check the data export documentation for details.)

`        
      },
      {
        heading: 'Extracting Keypoints',
        body: `The keypoints.py module contains functions to extract 2D keypoint locations for each class. 
The keypoints are generated by first defining a set of 3D keypoint locations in the object space for each class. These keypoints are typically defined based on the geometry of the object and the specific features that are relevant for pose estimation.
\n
Similar to bounding box extraction, the 3D keypoint locations are projected onto the 2D image plane using the camera's intrinsic parameters.
For each keypoint, its visibility is determined by these two steps:\n
1. Check if the keypoint is infront of the camera by evaluating the z-coordinate.\n
2. Perform a raycast from the camera to the keypoint location to check if there are any occluding objects in between.\n
\nFinally, the 2D keypoint locations are represented as an array of objects in the following format:\n
name: keypointname\n
x: x-coordinate in pixel\n
y: y-coordinate in pixel\n
inFrame: true if the keypoint is within the image frame, false otherwise\n
occluded: true if the keypoint is occluded by another object, false otherwise\n
(Note: The keypoint visibility information is crucial for training the pose estimation model, as it allows the model to learn to handle occlusions and missing keypoints effectively.)
`
      }
    ]

  },
  {
    title: 'Dataset Export',
    description:
      'Persist image frames, labels, and transformation records into a consistent dataset layout for training and reproducibility.',
    file: 'data generator/utils/dataformatter.py',
    to: '/synthetic-data/dataset-export',
    notes: [
      'Stores per-frame transformation context for replay and debugging.',
      'Keeps folder conventions stable across dataset versions.',
      'Exports images and labels in formats compatible with common training pipelines (COCO or YOLO).',
    ],
    sections: [
      {
        heading: 'COCO Format Export',
        body: `
The dataformatter.py module contains functions to export the generated dataset in the COCO format, which is a widely used format for object detection and
keypoint detection tasks. The COCO format organizes the dataset into a specific structure that includes images, annotations, and categories. 
The preferred export format for our dataset is COCO, as it allows us to include both bounding box and keypoint annotations in a single unified format.
Sometimes, we may want to load our dataset into Roboflow for pre-processing or merging with real dataset. At the time of writing, Roboflow supports uploading
annotated datasets only in the COCO format for keypoint detection.
\n
The export process involves the following steps:\n
1. Convert the generated annotations (bounding boxes and keypoints) into the COCO format, which includes defining the categories, images, and annotations in a specific JSON structure.\n
2. Bounding boxes need to be converted from the (x_min, y_min, x_max, y_max) format to the COCO format of (x_min, y_min, width, height) by calculating the width and height from the min and max coordinates.\n
3. Save the images in a designated folder, typically named 'images', and save the annotations in a JSON file, typically named '_annotations.coco.json', inside images folder alongside rendered images.\n

The resulting dataset will have the following structure:\n
/dataset_root\n
    /images\n
          0000001.png\n
          0000002.png\n
          ...\n
          _annotations.coco.json\n
    /labels (will be empty for COCO format, will contain txt files for YOLO format)\n
    /transformation_matrices (contains per-frame transformation matrices)\n
          000001.txt\n
          000002.txt\n
          ...\n       


The _annotations.coco.json file will be structured according to the COCO format specification.
Check the API documentation for DataFormatter for more details.

`
      }
    ]
  },
]
